name: copy files
on: [push]
jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "/home/runner/*"
        target: "/downloads"
