name: copy
on: [push, pull_request]

jobs:

  test:
    name: copy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Copy file
  # You may pin to the exact commit or the version.
  # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
        uses: canastro/copy-action@0.0.2
        with:
    # Source file
          source: C:\Users\svelpuri\action\a1
    # Target file
          target: D:\New folder
