name: copy
on: [push, pull_request]

jobs:

  test:
    name: copy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Copy file
  # You may pin to the exact commit or the version.
  # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
        uses: canastro/copy-action@0.0.2
        with:
    # Source file
          source: /var/cache
    # Target file
          target: /downloads/*
